---
- title: "Oregon Humane Society"
  url: "https://www.oregonhumane.org/adopt/?type=cats"
  match_set: 'class="animal-results"'
  match_item: 'class="result-item"'
  item_attributes:
      - Name: '<span class="name">([^<]+)</span>'
      - Breed: '<span class="breed">([^<]+)</span>'
        want:
          - Snowshoe
          - Siamese
      - Sex: '<span class="sex">([^<]+)</span>'
        want:
          - '"Male"'
      - Color: '<span class="color">([^<]+)</span>'
      - Age: '<span class="age">([^<]+)</span>'
      - Link: '<a href="([^\"]+)">'
  # If no wants are specified, every item will be assumed wanted.
  # If wants are specified, then the match mode can be loose (any
  # wanted value matches) or strict (every wanted value matches).
  # The default mode is loose. To make it strict, make this "all".
  wants: "all"
