---
- title: "Oregon Humane Society"
  url: "https://www.oregonhumane.org/adopt/?type=cats"
  match_set: 'class="animal-results"'
  match_item: 'class="result-item"'
  item_attributes:
      - Name: '<span class="name">([^<]+)</span>'
      - Breed: '<span class="breed">([^<]+)</span>'
      - Sex: '<span class="sex">([^<]+)</span>'
      - Color: '<span class="color">([^<]+)</span>'
      - Age: '<span class="age">([^<]+)</span>'
      - Link: '<a href="([^\"]+)">'
